### ISSUE TITLE
Some Webhook properties (filters, method, headers) do not exist on model

### ISSUE THREAD

**Issue by kevin-mitchell** [amplience/dc-management-sdk-js#82]
### Description

It looks like the [`Webhook` model](https://github.com/amplience/dc-management-sdk-js/blob/master/src/lib/model/Webhook.ts) does not have a number of useful or important properties defined on it, specifically:

* `filters`
* `method`
* `headers`
* `customPayload`

#### Steps to Reproduce

Create a new `Webhook` and attempt to 

#### Expected Results

```
    exampleWebhook.method = 'POST';
    exampleWebhook.headers = [
      { key: 'a-non-secret', value: 'asdfasd', secret: false },
      { key: 'a-secret', value: 'asdfasd', secret: true }
    ];

    exampleWebhook.customPayload = {
      type: 'text/x-handlebars-template',
      value:
        '{\n    asdfasdf: {{payload.name}},\n    body: {{payload.body}}\n}\n'
    };

    exampleWebhook.filters = [
      {
        type: 'equal',
        arguments: [
          {
            jsonPath: '$.payload.rootContentItem.contentTypeUri'
          },
          {
            value: 'a-great-schema.json'
          }
        ]
      }
    ];
```

The above should work without issue and TypeScript should not complain. 

#### Actual Results

![Screen Shot 2021-04-19 at 4 02 59 PM](https://user-images.githubusercontent.com/21270844/115313779-bf966380-a128-11eb-9600-b544332d7abf.png)

### Affected browsers/environments

*

### Versions

`v1.10.0`

### Other information

As far as I can tell, the actual webservice / API backend is perfectly happy accepting these values, so it seems useful to be able to set them on the Webhook model. As far as I can tell, they just don't exist on the model, which is inconvenient if you want to set these values when creating a Webhook. This may have been a design decision (of course I wouldn't know), but if not it would be great to have these properties available!

**Comment by easen-amp** [comment]
Webhook `filters`, `method`, `headers` & `customPayload` are recent additions to our Webhooks. I agree, I think these should be available in the SDK.

Thank you for opening a PR to add these properties 👍, I'll check it out now.

**Comment by kevin-mitchell** [comment]
This is fixed via https://github.com/amplience/dc-management-sdk-js/pull/83 - thank you very much for the work on the PR and closing this out :)
