### ISSUE TITLE
Listing content types is missing the `status` option.

### ISSUE THREAD

**Issue by philipbushnell-valtech** [amplience/dc-management-sdk-js#99]
### Description
Listing content types is missing the `status` option when using typescript (see https://amplience.com/docs/api/dynamic-content/management/index.html#operation/listContentTypes).

![image](https://user-images.githubusercontent.com/78373345/149144385-f5bc2b81-45da-40d9-a5b8-843f5872a7ba.png)

#### Steps to Reproduce
1. `const dc = new DynamicContent({ client_id, client_secret })`
2. `const hub = await dc.hubs.get(hubId)`
3. `hub.related.contentTypes.list({ ... })`

#### Expected Results
`status` is an available option to pass to this function.

#### Actual Results
It's missing, but the others (`page`, `size` and `sort`) exist.

### Versions
- dc-management-sdk-js: v1.14.0

**Comment by ashatch** [comment]
Thanks for highlighting. The status parameter is now supported, pending release.
